//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoomBooking.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoomBooking.Core.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hora de início da reserva não pode ser posterior a hora de término.
        /// </summary>
        public static string BookStartTimeMustBeFuture {
            get {
                return ResourceManager.GetString("BookStartTimeMustBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sala já está reservada neste horário.
        /// </summary>
        public static string RoomAlreadyBookedAtThisTime {
            get {
                return ResourceManager.GetString("RoomAlreadyBookedAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sala fecha as {0}.
        /// </summary>
        public static string RoomClosesAt {
            get {
                return ResourceManager.GetString("RoomClosesAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma sala deve fechar antes das 18:00.
        /// </summary>
        public static string RoomMustClosesBefore {
            get {
                return ResourceManager.GetString("RoomMustClosesBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uma sala só pode abrir após as 08:00.
        /// </summary>
        public static string RoomMustOpensAfter {
            get {
                return ResourceManager.GetString("RoomMustOpensAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sala só abre as {0}.
        /// </summary>
        public static string RoomOpensAt {
            get {
                return ResourceManager.GetString("RoomOpensAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hora de abertura da sala não pode ser posterior a hora de fechamento.
        /// </summary>
        public static string RoomStartTimeMustBeFuture {
            get {
                return ResourceManager.GetString("RoomStartTimeMustBeFuture", resourceCulture);
            }
        }
    }
}
